apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortner-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlshortner
  template:
    metadata:
      labels:
        app: urlshortner
    spec:
      containers:
        - name: urlshortner
          image: brianpzaide/urlshortner:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 4000
          env:
          - name: URLSHORTNER_DB_DSN
            valueFrom:
              secretKeyRef:
                name: dsn
                key: URLSHORTNER_DB_DSN
          command:
            - "sh"
            - "-c"
            - "while ! nc -z postgresql-service 5432; do sleep 3; done && ./urlshortner"
---

apiVersion: v1
kind: Service
metadata:
  name: urlshortner-service
spec:
  type: NodePort
  selector:
    app: urlshortner
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000