kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-pv
  labels:
    type: local
    app: db
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"