kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pvc
  labels:
    app: db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi