apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-postgresql
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        ports:
        - containerPort: 5432
          name: postgresdb
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdb
        - name: initdb-config
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: db-pvc
        - name: initdb-config
          configMap:
            name: postgres-initdb-config
---

apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  labels:
    app: postgres
spec:
  selector:
    app: postgresql
  ports:
   - port: 5432
